name: MordTeleport
version: ${project.version}
main: com.mordonia.mordteleport.MordTeleport
api-version: 1.13
authors: [AlexxSGames]
description: A teleportation plugin for Mordonia
website: mordoniamc.com
commands:
  mordtp:
    description: Main command used to create the teleporters.
